version: '3.9'

services:
  teslodb:
    image: mongo:4.4.6
    container_name: proyect-shop
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${PASSWORD}